name: example-python-ctypes
base: core22
version: '0.1'
summary: An example snap for a Python project using ctypes
description: |
  Shows how to create a snap for a Python application that uses ctypes to
  access a system library.

grade: devel
confinement: classic

apps:
  example-python-ctypes:
    # This refers to the installed location of the program at build-time.
    # When the snap is installed, it will be available as example-python-ctypes.
    command: bin/test-ctypes.py
    environment:
      LD_LIBRARY_PATH: /usr/lib:$LD_LIBRARY_PATH

parts:
  example-part:
    source: .
    plugin: python
    python-packages:
      - pip==20.0.2
